workaround for missing timespec_get
progress.c: In function 'now_ns':
progress.c:1009:5: error: implicit declaration of function 'timespec_get' [-Wimplicit-function-declaration]
 1009 |     timespec_get(&ts, TIME_UTC);
      |     ^~~~~~~~~~~~
progress.c:1009:23: error: 'TIME_UTC' undeclared (first use in this function)
 1009 |     timespec_get(&ts, TIME_UTC);
      |                       ^~~~~~~~
progress.c:1009:23: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [../../include/Make/Compile.make:32: OBJ.x86_64-w64-mingw32/progress.o] Error 1
make[3]: *** Waiting for unfinished jobs....
paths.c: In function 'G_owner':
paths.c:220:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  220 |     return (int)pSidOwner;
      |            ^
make[3]: Leaving directory '/d/a/grass/grass/lib/gis'
make[3]: Entering directory '/d/a/grass/grass/lib/proj'
test -d OBJ.x86_64-w64-mingw32 || mkdir -p OBJ.x86_64-w64-mingw32